### PR TITLE
Added non-ASCII examples; clarify path handling

### PR DESCRIPTION
**Pull request by bsittler**
While working on https://github.com/bsittler/async-cookies-api/pull/24 I noticed some badly worded parts of the explainer and the lack of non-ASCII examples

### CODE REVIEW

**Comment by bsittler** [comment]
@domenic @annevk What do you think of these proposed changes? I believe this clarifies path handling for read and write operations and gives examples with non-ASCII cookie values which should better explain the intent

**Comment by domenic** [comment]
I guess I'm not sure I entirely understand the processing model for the path stuff, but I can wait for precise spec text for that.

Non-ASCII examples are good. Maybe you want to give examples of how writing allows you to read back and get the same values?

**Comment by bsittler** [comment]
> I guess I'm not sure I entirely understand the processing model for the path stuff, but I can wait for precise spec text for that.

Yeah, this part needs a spec badly. Existing browser behavior appears to be somewhat inconsistent here.

> Non-ASCII examples are good. Maybe you want to give examples of how writing allows you to read back and get the same values?

Done, I think. Does it do what you meant?

**Comment by domenic** [comment]
Yeah, looks good!

**Pull request merged**
